name: CI/CD Rust Lambda + Frontend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install cargo-lambda
        run: cargo install cargo-lambda

      - name: Build Rust Lambda
        working-directory: fullstack-app-aws/backend
        run: cargo lambda build --release --arm64

      - name: Package Lambda
        working-directory: fullstack-app-aws/backend
        run: zip -j ../../lambda.zip target/lambda/jokes-api/bootstrap

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Build Frontend
        working-directory: fullstack-app-aws/frontend
        run: |
          npm install
          npm run build

      - name: Deploy Frontend to S3
        working-directory: fullstack-app-aws/frontend
        run: |
          aws s3 sync build/ s3://my-frontend-bucket --delete
          aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
